apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: banco-replicaset
  labels:
    app: banco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco
  template:
    metadata:
      labels:
        app: banco
    spec:
      containers:
      - name: banco
        image: gaellopes/banco-it-talent:v1
        ports:
        - containerPort: 3306